### ISSUE TITLE
Really like your ll command

### ISSUE THREAD

**Issue by ignamartinoli** [aerosol/tokyonight-kitty#3]
Hi, I use your Kitty colorscheme and I saw the screen capture of the repo. I really like how the colors are presented with the command `ll`. Could you please share how you accomplished that?

**Comment by aerosol** [comment]
Hey, it's https://github.com/ogham/exa

```
$ alias ls
ls='exa --icons'

$ alias ll
ll='ls -al'
```

**Comment by ignamartinoli** [comment]
Thanks!
